russophobic_words = {
                     'russkies':-10,
                     'ruskies':-10,
                     'rooskies':-10,
                     'invaders':-5,
                     'invade':-5,
                     'invaded':-5,
                     'oppressive':-5,
                     'opress':-5,
                     'opressing':-5,
                     'opression':-5,
                     'regime':-5, 
                     'autocratic':-6,
                     'autocracy':-6,
                     'kacaps':-10,
                     'threat':-4,
                     'poisoning':-3,
                     'polonium':-3,
                     'poison':-3,
                     'poisoned':-3,
                     'agression':-6,
                     'fuck':-4,
                     'attack':-3,
                     'war':-3,
                     'vodka':-2,
                     'pogroms':-3,
                     'embargo':-4,
                     'commies':-4,
                     'tortue':-4,
                     'tortued':-4,
                     'expansion':-5,
                     'bloodshed':-6,
                     'violence':-4,
                     'genocide':-6,
                     'genocide':-6,
                     'spy':-4,
                     'spies':-4,
                     'purges':-3,
                     'empire':-4,
                     'imperialistic':-5,
                     'gay': -2,
                     'threatened': -3,
                     'troll':-4,
                     'trolled': -4,
                     'trolling': -4,
                     'hack':-5,
                     'hacked': -5,
                     'hacking': -5,
                     'threatening': -4,
                     'kill': -3,
                     'killed': -3,
                     'killing':-3,
                     'backward':-5,
                     'backwards':-5,
                     'propaganda':-4
                      }
